name: Build

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [ "*" ]
  pull_requests:
    branches: [ "*" ]

jobs:

  build:
    name: Build waagent-rs
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        id: build
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get -y install rustup pkg-config libssl-dev
          rustup toolchain install stable
      - name: Build
        run: |
          cargo check
          cargo build --release
          ls -lha target/release
